#!/bin/sh

if [ $# != 2 ]; then
    echo "Usage: ./aoc <year> <day>"
    exit 1
fi

if [ -f ".env" ]; then
    export $(grep -v '^#' .env | xargs)
fi

if [ -z "$AOC_COOKIE" ]; then
    echo "Cookie not provided. Fetch from browser devtools and set using:"
    echo ""
    echo "  export AOC_COOKIE=\"<aoc cookie>\""
    echo ""
    echo "Or store it in a .env file alongside this script:"
    echo "  echo \"AOC_COOKIE=<aoc cookie>\" > .env"
    exit 1
fi

year=$1
day=$2

day_formatted=$(printf "%02d" $day)
notebook_path="./solutions/$year/Day $day_formatted.ipynb"
puzzle_path="./solutions/$year/puzzle_inputs/$day_formatted.txt"

mkdir -p "solutions/$year/puzzle_inputs"

if [ ! -f "$notebook_path" ]; then
    cp ./template.ipynb "$notebook_path"
    sed -i "s/%%DAY/$day_formatted/g" "$notebook_path"
fi

if [ ! -f "$puzzle_path" ]; then
    curl --cookie "$AOC_COOKIE" https://adventofcode.com/$year/day/$day/input -s -o "$puzzle_path"
fi

less $puzzle_path

